version: '3.1'

networks:
  network-net:
    driver: bridge

services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    networks:
      - network-net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fornecedor